"""'textmaxsize'

Revision ID: 1f08e08b107e
Revises: 41a83a4d7d01
Create Date: 2024-03-22 15:30:03.257825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f08e08b107e'
down_revision: Union[str, None] = '41a83a4d7d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_texts', 'content',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=2560),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_texts', 'content',
               existing_type=sa.String(length=2560),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###
