"""'ArticleContent_update'

Revision ID: 2bc01c2322dd
Revises: 2d1ff56e36cc
Create Date: 2024-03-22 13:38:00.891027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc01c2322dd'
down_revision: Union[str, None] = '2d1ff56e36cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_content', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_content', 'position')
    # ### end Alembic commands ###
