"""'ArticleContent_update'

Revision ID: 41a83a4d7d01
Revises: 2bc01c2322dd
Create Date: 2024-03-22 13:41:25.454747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a83a4d7d01'
down_revision: Union[str, None] = '2bc01c2322dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
