"""test6

Revision ID: 3b0ddd38b71b
Revises: f99661642694
Create Date: 2024-03-18 23:22:34.283543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0ddd38b71b'
down_revision: Union[str, None] = 'f99661642694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('test', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
