"""db_structure update 1

Revision ID: 5aec435121a1
Revises: 37752acc0e08
Create Date: 2024-03-20 09:51:03.861150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aec435121a1'
down_revision: Union[str, None] = '37752acc0e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quniq_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('articles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'articles', ['parent_id'], ['id'])
    op.drop_column('articles', 'edited')
    op.drop_column('articles', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created', sa.DATETIME(), nullable=False))
    op.add_column('articles', sa.Column('edited', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'company_id')
    op.drop_column('articles', 'parent_id')
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    op.drop_table('companies')
    # ### end Alembic commands ###
